### ISSUE TITLE
깃헙은 커밋하는게 중요한게 아니라 내역이 중요해요

### ISSUE THREAD

**Issue by sunwoo0706** [qoxogus/TIL#1]
(edited) 태현아 커밋을 채우고 싶은 너의 마음은 알겠어, 그런데 저런식의 커밋은 오히려 너에게 독이 될것 같아, 커밋보다 그 내용에 더 집중해줬으면 좋겠다.

**Comment by MagicalLas** [comment]
커밋 내용을 보긴 하지만, 모든 커밋 내용을 보지는 않을 것 같긴 하네요.
그러나 깃을 잘 사용하는건 중요해요. 실제 회사에서도 커밋을 잘 작성하지 않는 경우도 있거든요ㅠㅠ

> 어느 누가 님처럼 하나요

이런 표현은 되도록이면 하지 않는게 좋지 않을까요? 너무 공격적인 것 같습니다.

**Comment by Goolgae** [comment]
친구여서 잘되는 마음에 한말이었습니다. 근데 누구세요??

**Comment by sunwoo0706** [comment]
관계를 모르시는분들은 그렇게 느끼시실수도 있겠네요. 불편드려 죄송합니다.

**Comment by MagicalLas** [comment]
앗 아니에요. 그러나 이런게 보일 수도 있다는걸 알아주셨으면 하여 추가적으로 글을 작성했던 것입니다.
열심히 하려는 모습이 보기 좋은 것 같아요.

좋은 하루 보내세요!

**Comment by sunwoo0706** [comment]
감사합니다

**Comment by qoxogus** [comment]
제가 많이 부족해서 도움주는 친구입니다. 감사합니다!!!

2021년 1월 5일 (화) 오후 3:25, Las <notifications@github.com>님이 작성:
